#!/usr/bin/env python3
# backend/econ.json (src/tools/econ_export.js) + backend/limits.json (src/tools/min_steps.js) → backend/holdor_econ_data.sql
# The game's own price tables and the fastest possible battles, for the server (backend v5). Re-run after any balance change.
import json, os
B = os.path.dirname(os.path.abspath(__file__))
econ = json.load(open(os.path.join(B, 'econ.json')))
lim = json.load(open(os.path.join(B, 'limits.json')))
q = lambda v: "'" + json.dumps(v, separators=(',', ':')).replace("'", "''") + "'::jsonb"
out = ['-- GENERATED by backend/gen_econ_sql.py from econ.json (game v%s) and limits.json — do not edit by hand.' % econ['version'],
       '-- Run in Supabase after holdor_v5.sql (and again after any balance change). Safe to re-run.', '']
keys = ['max', 'sk_cap', 'card_gold', 'sk_cost', 'army_cost', 'upg', 'pack', 'ach', 'chests', 'exchange', 'deal_unlock', 'hold_attempts', 'cards']
out.append('insert into econ_config (k, v) values')
out.append(',\n'.join('  (%s, %s)' % ("'" + k + "'", q(econ[k])) for k in keys))
out.append('on conflict (k) do update set v = excluded.v;')
out.append('')
rows = ['  (%s, %d, %d, %d)' % ("'stage'", int(k), v['min_steps'], v['kills']) for k, v in sorted(lim['stages'].items(), key=lambda x: int(x[0]))]
# hold: claimed waves W means wave W+1 had started — its first tick is the least possible; kills are capped at what waves 1..W+1 spawn
hw = {int(k): v for k, v in lim['hold_wave'].items()}
top = max(hw)
for w in range(0, top):
    t = hw.get(w + 1, [0, 0])[0]; k = hw.get(min(w + 2, top), [0, 0])[1]
    rows.append('  (%s, %d, %d, %d)' % ("'hold'", w, t, k))
out.append('delete from battle_limits;')
out.append('insert into battle_limits (kind, n, min_steps, max_kills) values')
out.append(',\n'.join(rows) + ';')
# beyond the measured waves: the last measured gap per wave keeps growing the minimum
gap = hw[top][0] - hw[top - 1][0]; kgap = hw[top][1] - hw[top - 1][1]
out.append("insert into econ_config (k, v) values ('hold_tail', %s) on conflict (k) do update set v = excluded.v;" % q({'last': top - 1, 'step_gap': gap, 'kill_gap': kgap}))
out.append('')
out.append("select count(*) filter (where kind = 'stage') as stages, count(*) filter (where kind = 'hold') as hold_waves from battle_limits;")
open(os.path.join(B, 'holdor_econ_data.sql'), 'w').write('\n'.join(out) + '\n')
print('wrote holdor_econ_data.sql ·', len(lim['stages']), 'stages ·', top, 'hold waves')
