# The 50-stage road north. pos = pin on the 720-wide board map (y<0 = the strip beyond the Wall drawn by code).
# lay: layout kind for the road generator — one | merge (two entries, one gate) | fork (one entry, two gates) | twin (two roads, two gates) | triple
STAGES = [
 # ---- Dorne ----
 dict(n='Sunspear', sub='Dorne · the Martells\' seat', biome='desert', pos=(606,1150), lay='one', sea='R'),
 dict(n='Salt Shore', sub='Dorne · the Summer Sea', biome='desert', pos=(440,1166), lay='one', sea='L'),
 dict(n='Yronwood', sub='Dorne', biome='desert', pos=(397,1100), lay='one'),
 dict(n='The Boneway', sub='Dorne · the mountain road', biome='desert', pos=(371,1040), lay='one', rocky=True),
 dict(n="Prince's Pass", sub='The Dornish Marches', biome='desert', pos=(296,1058), lay='one', rocky=True),
 dict(n='Sandstone', sub='Dorne · the deep sand', biome='desert', pos=(275,1154), lay='one'),
 dict(n='Starfall', sub='Dorne · House Dayne', biome='desert', pos=(206,1128), lay='merge', sea='L'),
 # ---- The Reach ----
 dict(n='The Arbor', sub='The Reach · the vineyard isle', biome='coast', pos=(62,1176), lay='one', sea='R'),
 dict(n='Oldtown', sub='The Reach · the Citadel', biome='city', pos=(114,1093), lay='one'),
 dict(n='Uplands', sub='The Reach', biome='reach', pos=(175,1071), lay='merge'),
 dict(n='Highgarden', sub='The Reach · the Tyrells\' seat', biome='reach', pos=(192,1002), lay='one', river=330),
 dict(n='Old Oak', sub='The Reach', biome='reach', pos=(105,915), lay='merge'),
 dict(n='Cider Hall', sub='The Reach · the orchards', biome='reach', pos=(278,968), lay='one', mod='clear'),
 dict(n='Tumbleton', sub='The Reach · the Mander', biome='river', pos=(406,913), lay='twin', river=360),
 # ---- The Stormlands ----
 dict(n='Stonehelm', sub='The Stormlands', biome='storm', pos=(472,985), lay='one'),
 dict(n="Storm's End", sub='The Stormlands · the Baratheons\' seat', biome='storm', pos=(548,938), lay='merge', sea='R', boss=True),
 dict(n='The Kingswood', sub='The Crownlands · the old forest', biome='forest', pos=(494,862), lay='one'),
 # ---- The Crownlands ----
 dict(n="King's Landing", sub='The Crownlands · the capital', biome='city', pos=(500,812), lay='twin', boss=True),
 dict(n='Dragonstone', sub='The Narrow Sea · the Targaryens\' seat', biome='ash', pos=(628,778), lay='one', sea='L'),
 dict(n='Maidenpool', sub='The Riverlands · the Bay of Crabs', biome='coast', pos=(506,728), lay='merge', sea='R'),
 # ---- The Riverlands & the Westerlands ----
 dict(n='Harrenhal', sub='The Riverlands · the burnt castle', biome='ash', pos=(415,712), lay='twin', mod='longnight', boss=True),
 dict(n='Stoney Sept', sub='The Riverlands', biome='river', pos=(327,775), lay='one', river=300),
 dict(n="Clegane's Keep", sub='The Westerlands', biome='mountain', pos=(162,872), lay='merge'),
 dict(n='Lannisport', sub='The Westerlands · the harbour city', biome='city', pos=(110,812), lay='one', sea='L'),
 dict(n='Casterly Rock', sub='The Westerlands · the Lannisters\' seat', biome='mountain', pos=(107,760), lay='fork', boss=True),
 dict(n='The Golden Tooth', sub='The Westerlands · the gold road', biome='mountain', pos=(215,765), lay='merge', mod='clear'),
 dict(n='Riverrun', sub='The Riverlands · the Tullys\' seat', biome='river', pos=(254,725), lay='twin', river=280),
 dict(n='Ashemark', sub='The Westerlands', biome='mountain', pos=(164,668), lay='one'),
 # ---- The Iron Islands & the Trident ----
 dict(n='Pyke', sub='The Iron Islands · the Greyjoys\' seat', biome='sea', pos=(115,610), lay='merge', sea='L'),
 dict(n='Seagard', sub='The Riverlands · the Mallisters', biome='coast', pos=(263,610), lay='fork', sea='L'),
 dict(n='The Twins', sub='The Riverlands · the Freys\' crossing', biome='river', pos=(300,588), lay='twin', river=340, boss=True),
 dict(n='Saltpans', sub='The Riverlands · the salt flats', biome='river', pos=(432,670), lay='merge', river=250),
 # ---- The Vale ----
 dict(n='The High Road', sub='The Vale · the mountain pass', biome='vale', pos=(414,630), lay='one'),
 dict(n='The Eyrie', sub='The Vale · the Arryns\' seat', biome='vale', pos=(474,607), lay='merge', mod='blizzard', boss=True),
 dict(n='Gulltown', sub='The Vale · the harbour', biome='sea', pos=(579,618), lay='fork', sea='R'),
 dict(n="Heart's Home", sub='The Vale', biome='vale', pos=(527,557), lay='twin'),
 dict(n='The Grey Glen', sub='The Vale', biome='vale', pos=(450,527), lay='merge'),
 # ---- The Neck ----
 dict(n='Moat Cailin', sub='The Neck · three towers', biome='swamp', pos=(320,428), lay='triple', mod='wildhunt', ponds=3, boss=True),
 # ---- The North ----
 dict(n='White Harbor', sub='The North · the Manderlys', biome='northcity', pos=(396,368), lay='twin', sea='R'),
 dict(n='Barrowton', sub='The North · the barrowlands', biome='snow', pos=(204,326), lay='merge'),
 dict(n='The Rills', sub='The North', biome='snow', pos=(106,300), lay='one', mod='blizzard', river=320),
 dict(n='Deepwood Motte', sub='The North · the wolfswood', biome='snow', pos=(186,181), lay='merge', forest=True),
 dict(n='Winterfell', sub='The North · the Starks\' seat', biome='snow', pos=(295,245), lay='twin', boss=True),
 dict(n='The Dreadfort', sub='The North · the Boltons', biome='snow', pos=(432,200), lay='fork', mod='longnight'),
 dict(n='Karhold', sub='The North · the Karstarks', biome='snow', pos=(522,130), lay='merge', sea='R'),
 dict(n='The Gift', sub='The North · the Night\'s Watch lands', biome='snow', pos=(395,88), lay='fork'),
 # ---- The Wall & beyond ----
 dict(n='Castle Black', sub='The Wall · the Night\'s Watch', biome='wall', pos=(320,42), lay='triple', boss=True),
 dict(n='The Fist of the First Men', sub='Beyond the Wall', biome='wall', pos=(262,-86), lay='merge', mod='blizzard'),
 dict(n='Hardhome', sub='Beyond the Wall · the free folk', biome='wall', pos=(566,-62), lay='twin', sea='R'),
 dict(n='The Lands of Always Winter', sub='Beyond the Wall · the heart of winter', biome='wall', pos=(430,-160), lay='triple', mod='longnight', boss=True),
]
assert len(STAGES) == 50, len(STAGES)
# one new kind of the dead per stage (early) — the full list of 30 arrives by stage 45
POOLS = {1:['axe','sword'],2:['child'],3:['archer'],4:['hound'],5:['crawler'],6:['spear'],7:['wolf'],8:['walker'],9:['shield'],10:['crypt'],
         11:['giant'],12:['boar'],13:['rider'],14:['spider'],15:['berserk'],17:['cat'],20:['thenn'],22:['necro'],23:['bear'],25:['elk'],
         27:['raven'],29:['eagle'],31:['wraith'],33:['bat'],35:['skin'],37:['chief'],39:['outrider'],41:['mammoth'],43:['shade'],45:['brood']}
INTRO = {
 1:'The dead rise in Dorne first. Axemen and swordsmen walk the road — build Watchtowers along it.',
 2:'Wight children: tiny and quick. They come in crowds.',
 3:'New: wight archers stop far from the gate and shoot it. Kill them before they stop.',
 4:'Wight hounds hunt in packs of three. Fast, fragile.',
 5:'Crawlers ignore every slow. Only damage stops them.',
 6:'Spearmen: slow and tough. Dragonglass and Watch keeps hold them.',
 7:'Wight direwolves: fast packs. Keep your men on the road.',
 8:'New: White Walkers. Kill one and every wight near it falls with it. Dragonglass ×3.',
 9:'Shieldmen shrug off arrows and bolts. Fire and steel work better.',
 10:'Crypt wights split into two axemen when they fall.',
 11:'New: wight giants walk past your champion unless it can Challenge them. Scorpions hit them hardest.',
 12:'Boars charge past every blocker — only towers stop them.',
 13:'Wight riders gallop past your men. Put towers on the long straights.',
 14:'Ice spiders web your towers and ignore slows.',
 15:'Frenzied wights rage at half health: faster and harder.',
 16:"Storm's End: a giant at every sixth wave. Hold the Stormlands.",
 17:'Shadowcats are invisible until they are close to a tower.',
 18:"King's Landing: two roads, two gates. Hodor holds one — tap a gate to send him.",
 19:'New: an undead dragon flies straight at the gate. Only Scorpions and Dracarys truly hurt it.',
 20:'Thenn wights wear armour: Scorpions and fire.',
 21:'The Long Night: enemies +15% speed. A Walker Lieutenant comes every 10 waves — Dragonglass ignores its armour.',
 22:'Cold necromancers raise the recently dead. Kill them first.',
 23:'Wight bears knock your men down.',
 25:'The Rock: two gates from one road. Watch where the horde splits.',
 27:'Dead ravens dive at your towers and blind them.',
 29:'Ice eagles fly straight at the gate.',
 31:'The Twins: two crossings, wraiths that shrug off arrows. Weirwood slows them.',
 33:'Cave bats swarm in threes over the walls.',
 34:'Blizzard: tower range −15%. Build close to the road.',
 35:'Skinchangers heal the horde around them.',
 37:'Wildling chieftains hasten the dead nearby.',
 38:'Moat Cailin: three roads, three towers. Wild Hunt — twice the giants.',
 39:'Walker outriders charge in ice armour.',
 41:'Wight mammoths: huge, armoured, slow.',
 43:'Winterfell: shades hide in the snow. Everything the South has taught you.',
 45:'Broodmothers birth ice spiders as they walk.',
 47:'Castle Black: three gates in the Wall. Hold them all.',
 48:'The Fist of the First Men: a blizzard on the ringwall.',
 49:'Hardhome: two roads from the sea.',
 50:'The Lands of Always Winter. The Night King comes with the final wave. When he falls, his dead fall with him. Hold the door.',
}
